### PR TITLE
Fixes 'basestring' no longer being available in Python 3.5

### PR DESCRIPTION
**Pull request by lizadaly**
pytracery's README example wasn't working in Python 3.5, and no test covered that case, so I wrote a test that exposed the problem (`basestring` has been removed from the standard library) and added a test and fix (which requires a new entry in requirements.txt). Tests still pass in 2.7.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -78,4 +78,5 @@ celerybeat-schedule
 .env
 
 # Spyder project settings
-.spyderproject
\ No newline at end of file
+.spyderprojectvenv
+venv
```
Comment (hugovk) [inline .gitignore]: Is this meant to be `.spyderproject` replaced by `.spyderprojectvenv` and `venv` added?

Or just `venv` added?

File: requirements.txt [hunk 2]
```diff
@@ -0,0 +1,2 @@
+jsonschema
```
Comment (hugovk) [inline requirements.txt]: Where is `jsonschema` needed?

File: requirements.txt [hunk 3]
```diff
@@ -0,0 +1,2 @@
...
+future
```
Comment (hugovk) [inline requirements.txt]: Is `future` missing for some version and need to be pip installed? Or does `past` come from it and is missing in some built in versions?

**Comment by hugovk** [comment]
Python 3.2 failed on the CI.
```
    from future.utils import PY3
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/future/utils/__init__.py", line 538
    return isinstance(obj, type(u''))
                                  ^
SyntaxError: invalid syntax
======================================================================
ERROR: Failure: ImportError (cannot import name PY3)
```

https://pypi.python.org/pypi/future doesn't include Python 3.2 as a supported version.

Many Python libraries are dropping support for Python 3.2, so I'd be inclined to save the bother of getting this to work in 3.2 and simply removing support too. CPython 3.2 itself is no longer supported: https://en.wikipedia.org/wiki/CPython#Version_history

File: .gitignore (hunk 1 above)
Comment (lizadaly) [inline .gitignore]: Yes it was broken, and not necessary to be in the repo anyway. Reverted.

**Comment by aparrish** [comment]
I'm very happy to drop 3.2 support, for the record.

File: requirements.txt (hunk 2 above)
Comment (lizadaly) [inline requirements.txt]: I swore I saw this as a dependency in the original code, but of course it's not there. Removed.

**Comment by hugovk** [comment]
I can remove 3.2 in another PR, if you'd like.

File: requirements.txt (hunk 3 above)
Comment (lizadaly) [inline requirements.txt]: `past` comes from `future`: http://python-future.org/reference.html#module-past.builtins

**Comment by aparrish** [comment]
yup, I'm gonna merge this. @hugovk if you don't mind doing a PR for removing 3.2 from the tests, that would be great! then I'll push this to pypi later in the afternoon.

**Comment by aparrish** [comment]
thanks @lizadaly :)

**Comment by hugovk** [comment]
There we go: PR https://github.com/aparrish/pytracery/pull/20
